repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
    -   id: golangci-lint-full
