name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Cache nix store
      uses: nix-community/cache-nix-action@v5
      with:
        primary-key: nix-${{ runner.os }}-${{ env.NIX_PATH }}-${{ hashFiles('**/*.nix') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: nix-shell --run "pre-commit run --all-files --show-diff-on-failure --color=always"
