name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Cache nix store
      id: cache-nix-store
      uses: actions/cache@v4
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-shell-${{ env.NIX_PATH }}-${{ hashFiles('**/shell.nix') }}

    - name: Run pre-commit
      run: nix-shell --run "pre-commit run --all-files --show-diff-on-failure --color=always"
